version: '3'
services:
  app:
    build: .
    restart: always
    volumes:
      - ./src:/gany/src
    ports:
      - 3123:3123
    depends_on:
      - mongo
      - redis
      - influx
    command: ['node', 'src/run.js']
  hourly_ticker_data_cron:
    build: .
    restart: always
    volumes:
      - ./src:/gany/src
    depends_on:
      - influx
    command: ['node', 'src/cron/hourly_ticker_data_cron.js']
  daily_ticker_data_cron:
    build: .
    restart: always
    volumes:
      - ./src:/gany/src
    depends_on:
      - influx
    command: ['node', 'src/cron/daily_ticker_data_cron.js']
  gany_charts:
    image: carlosero/ganycharts
    restart: always
  mongo:
    image: mongo
    restart: always
    volumes:
      - $PWD/.ganydata/mongo:/data/db
  redis:
    image: redis
    restart: always
    volumes:
      - $PWD/src/config/redis.conf:/usr/local/etc/redis/redis.conf
      - $PWD/.ganydata/redis:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
  influx:
    image: influxdb
    environment:
      - INFLUXDB_DB=gany
      - INFLUXDB_USER=${INFLUXDB_USER:-ganyuser}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD:-ganypassword}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER:-ganyadmin}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-ganyadminpassword}
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    volumes:
      - $PWD/.ganydata/influx:/var/lib/influxdb
